ocm:
  api_url: "https://api.openshift.com"
  token: "your-token"

mcp:
  api_url: "https://your-mcp-instance"
  credentials:
    username: "your-username"
    password: "your-password"

server:
  host: "0.0.0.0"
  port: 8000
  debug: false
